// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using junie_des_1942stats.PlayerTracking;

#nullable disable

namespace junie_des_1942stats.Migrations
{
    [DbContext(typeof(PlayerTrackerDbContext))]
    [Migration("20251022082500_AddTournamentSupport")]
    partial class AddTournamentSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            // Note: This is a simplified designer file focusing on the tournament changes
            // The full model would be regenerated by EF Core migrations
            
            modelBuilder.Entity("junie_des_1942stats.PlayerTracking.Tournament", b =>
                {
                    b.Property<string>("TournamentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TournamentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("TournamentId");

                    b.HasIndex("ServerGuid", "StartTime");

                    b.HasIndex("MapName");

                    b.HasIndex("IsActive");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("junie_des_1942stats.PlayerTracking.TournamentRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoundId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("RoundId")
                        .IsUnique();

                    b.ToTable("TournamentRounds");
                });
#pragma warning restore 612, 618
        }
    }
}