---
apiVersion: v1
kind: Namespace
metadata:
  name: bf42-stats
---
# Role in the 'bf42-stats' namespace to allow managing deployments
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bf42-stats
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# RoleBinding to link the service account from 'jenkins-ci' to the role in 'bf42-stats'
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: bf42-stats
  name: jenkins-deployment-binding
subjects:
- kind: ServiceAccount
  name: default  # Replace with your Jenkins agent’s service account name if different
  namespace: jenkins-ci
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io