{
 "title": "site stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId" }
  ]
 },
 "panels": [
  {
   "title": "Player Visits",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"junie-des-1942stats\"} | json | RequestPath=~\"/stats/players/[^/]+$\" | label_format RequestPath=\"{{.RequestPath}}\", TraceId=\"{{.TraceId}}\""
    }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 30, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "${traceId:raw}", "tableType": "traces" }
   ]
  },
  {
   "title": "Server Visits",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"junie-des-1942stats\"} | json | RequestPath=~\"/stats/servers/[^/]+$\" | label_format RequestPath=\"{{.RequestPath}}\", TraceId=\"{{.TraceId}}\""
    }
   ]
  }
 ]
}